#!/usr/bin/env bash
# Gives information about a file

filed="school"
if [ -e $filed ];
then
    echo "school file exists"
    if [ -s $filed ];
    then
	echo "school file is not empty"
    else
	echo "school file is empty"
    fi
    if [ -f $filed ];
    then
	echo "school is a regular file"
    fi
else
    echo "school file does not exist"
fi
