#!/usr/bin/env bash
#  Creates a file containing its PID
#+ Displays "To infinity and beyond" indefinitely
#+ Displays "I hate the kill command" when receiving a SIGTERM signal
#+ Displays "Y U no love me?!" when receiving a SIGINT signal
#+ Deletes the file containing its PID and terminates itself
#+ when receiving a SIGQUIT or SIGTERM signal

echo $$ > /var/run/myscript.pid
while true;
do
    echo "To infinity and beyond"
    sleep 2
    trap 'echo "I hate the kill command"' 15
    trap 'echo "Y U no love me?!"' 2
    trap 'kill -15 $(cat /var/run/myscript.pid) && rm /var/run/myscript.pid' 3
done
