#!/usr/bin/env bash
#  Displays "To infinity and beyond" indefinitely
#+ with "sleep 2" in between each iteration

statement="To infinity and beyond"
while true;
do
    echo "$statement"
    sleep 2
done
